name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5

      - name: 🔢 Adjust version number
        shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          version="${version#v}"
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/hwmon_temp/manifest.json"

      - name: 📦 Created zipped release package
        run: |
          cd "${{ github.workspace }}/custom_components/hwmon_temp"
          zip hwmon_temp.zip -r ./

      - name: ⬆️ Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GHCR_TOKEN }}
          file: '${{ github.workspace }}/custom_components/hwmon_temp/hwmon_temp.zip'
          asset_name: hwmon_temp.zip
          tag: ${{ github.ref }}
          overwrite: true
